# Generated by Django 2.1.4 on 2020-08-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Fill This', max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('field', models.TextField(choices=[('text', 'TextField'), ('choice', 'Choices'), ('multipleChoices', 'MultipleChoice'), ('date&time', 'DateTime'), ('dropDown', 'DropDown'), ('fileUpload', 'FileUpload'), ('number', 'NumberOnly')])),
            ],
        ),
    ]
