# Generated by Django 2.1.4 on 2020-08-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20200824_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='label',
            field=models.CharField(default='Label', max_length=50),
        ),
    ]
