# Generated by Django 2.1.4 on 2020-08-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_field_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='title',
        ),
    ]
