# Generated by Django 2.1.4 on 2020-08-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='slug',
        ),
    ]
