# Generated by Django 2.1.4 on 2020-08-26 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_remove_form_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Section'),
        ),
    ]
