# Generated by Django 2.1.4 on 2020-08-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_field_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field',
            field=models.TextField(choices=[('text', 'text'), ('choice', 'choice'), ('multipleChoices', 'multipleChoices'), ('datetime', 'datetime'), ('dropDown', 'dropDown'), ('fileUpload', 'fileUpload'), ('number', 'number')]),
        ),
        migrations.AlterField(
            model_name='form',
            name='publishDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
